const messages = [
  "This is where it all begins...",
  "Commit committed",
  "Version control is awful",
  "COMMIT ALL THE FILES!",
  "The same thing we do every night, Pinky - try to take over the world!",
  "Lock S-foils in attack position",
  "This commit is a lie",
  "I'll explain when you're older!",
  "Here be Dragons",
  "Reinventing the wheel. Again.",
  "This is not the commit message you are looking for",
  "Batman! (this commit has no parents)",
  "The early bird catches the worm.",
  "Actions speak louder than words.",
  "Where there's smoke, there's fire.",
  "You can't judge a book by its cover.",
  "You can't have your cake and eat it too.",
  "There's no place like home.",
  "Practice makes perfect.",
  "Rome wasn't built in a day.",
  "Don't count your chickens before they hatch.",
  "Better safe than sorry.",
  "You can lead a horse to water, but you can't make it drink.",
  "A picture is worth a thousand words.",
  "Necessity is the mother of invention.",
  "The proof of the pudding is in the eating.",
  "You can't make an omelette without breaking eggs.",
  "Where there's muck there's brass.",
  "The best things in life are free.",
  "You can't have too much of a good thing.",
  "Every cloud has a silver lining.",
  "Time is money.",
  "No pain, no gain.",
  "A friend in need is a friend indeed.",
  "You can't teach an old dog new tricks.",
  "There's no smoke without fire.",
  "Actions speak louder than words.",
  "You can't judge a book by its cover.",
  "Every man has his price.",
  "Where there's life, there's hope.",
  "The early bird catches the worm.",
  "All good things come to an end.",
  "The grass is always greener on the other side.",
  "There's no time like the present.",
  "Time flies when you're having fun.",
  "Honesty is the best policy.",
  "What goes around comes around.",
  "You can't have your cake and eat it too.",
  "Where there's smoke, there's fire.",
  "All's well that ends well.",
  "An apple a day keeps the doctor away.",
  "Where there's muck there's brass.",
  "You can't make an omelette without breaking eggs.",
  "Birds of a feather flock together.",
  "Time heals all wounds.",
  "You can lead a horse to water, but you can't make it drink.",
  "A picture is worth a thousand words.",
  "The proof of the pudding is in the eating.",
  "A friend in need is a friend indeed.",
  "The best things in life are free.",
  "You can't have too much of a good thing.",
  "Every cloud has a silver lining.",
  "Time is money.",
  "No pain, no gain.",
  "You can't teach an old dog new tricks.",
  "There's no smoke without fire.",
  "Actions speak louder than words.",
  "You can't judge a book by its cover.",
  "Every man has his price.",
  "Where there's life, there's hope.",
  "The early bird catches the worm.",
  "All good things come to an end.",
  "The grass is always greener on the other side.",
  "There's no time like the present.",
  "Time flies when you're having fun.",
  "Honesty is the best policy.",
  "What goes around comes around.",
  "You can't have your cake and eat it too.",
  "Where there's smoke, there's fire.",
  "It's just the beginning",
  "The sky's the limit",
  "Never give up",
  "Believe in yourself",
  "Make every moment count",
  "Chase your dreams",
  "Life is an adventure",
  "Take the risk or lose the chance",
  "The power of positive thinking",
  "Success is a journey, not a destination",
  "Don't look back, you're not going that way",
  "A goal without a plan is just a wish",
  "Work hard, play harder",
  "Every day is a new opportunity",
  "You miss 100% of the shots you don't take",
  "Happiness is not something ready made. It comes from your own actions",
  "You are the master of your own destiny",
  "What you do today can improve all your tomorrows",
  "Life is too short to waste time",
  "Do what makes you happy",
  "Life is a gift, cherish it",
  "Today is a good day to have a good day",
  "Be the change you wish to see in the world",
  "Success is not final, failure is not fatal: it is the courage to continue that counts",
  "Do not let yesterday take up too much of today",
  "In the end, we will remember not the words of our enemies, but the silence of our friends",
  "Be yourself; everyone else is already taken",
  "The only way to do great work is to love what you do",
  "The greatest glory in living lies not in never falling, but in rising every time we fall",
  "The only limit to our realization of tomorrow will be our doubts of today",
  "If you want to live a happy life, tie it to a goal, not to people or things",
  "You can't build a reputation on what you are going to do",
  "Success is not how high you have climbed, but how you make a positive difference to the world",
  "The future belongs to those who believe in the beauty of their dreams",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough",
  "Hardships often prepare ordinary people for an extraordinary destiny",
  "Life is like a camera, focus on the good times, develop from the negatives, and if things don't work out, take another shot",
  "Don't wait for opportunities, create them",
  "You can't have a better tomorrow if you are thinking about yesterday all the time",
  "We cannot solve our problems with the same thinking we used when we created them",
  "Success is not the key to happiness. Happiness is the key to success",
  "Don't let yesterday take up too much of today",
  "Your only limit is the amount of love you have for yourself",
  "The secret of getting ahead is getting started",
  "Don't watch the clock; do what it does. Keep going",
  "The only way to do great work is to love what you do",
  "You are never too old to set another goal or to dream a new dream",
  "Dream big, work hard, stay focused, and surround yourself with good people",
  "You can't change the past, but you can change your attitude towards it",
  "The future is bright if you have the courage to see it",
  "The only limit to our realization of tomorrow will be our doubts of today",
  "Change the way you look at things and the things you look at change",
  "The difference between ordinary and extraordinary is that little extra",
  "What you",
  "Life is a journey, enjoy the ride",
  "Think outside the box",
  "Every obstacle is an opportunity",
  "Dreams come true if you pursue them",
  "Lead by example",
  "Never stop learning",
  "Be the solution, not the problem",
  "Happiness is a state of mind",
  "Success is a combination of luck and hard work",
  "Don't wait for the perfect moment, take the moment and make it perfect",
  "Be fearless in the pursuit of what sets your soul on fire",
  "Do what you love, love what you do",
  "Let your passion drive your success",
  "Be the change you wish to see",
  "Take action, not just words",
  "Life is a canvas, paint it with love and happiness",
  "Make today count",
  "Great things never came from comfort zones",
  "Create the life you want to live",
  "Chase your passions, not your pension",
  "Life is 10% what happens to you and 90% how you react to it",
  "You are capable of more than you know",
  "Act as if what you do makes a difference, it does",
  "Take chances and never regret",
  "Create your own opportunities",
  "The future is yours to create",
  "Never settle for less than you deserve",
  "The journey is the reward",
  "Be true to yourself",
  "Dream big, act bigger",
  "Stay focused, stay positive",
  "Success is a journey, not a destination",
  "The only limit is the one you set for yourself",
  "Successful people don't wait for opportunities, they create them",
  "Believe in your dreams and they will become reality",
  "Let your light shine bright",
  "Happiness is a choice, choose wisely",
  "The only way to do great work is to love what you do",
  "Be thankful for every moment",
  "Take care of yourself, it's the best investment you can make",
  "Life is too short to be anything but happy",
  "Every day is a chance to start over",
  "If you want to live a happy life, tie it to a goal, not to people or things",
  "Don't let fear stop you from achieving greatness",
  "Do something today that your future self will thank you for",
  "Life is a journey, make the most of it",
  "The key to success is determination",
  "Create your own happiness",
  "Chase your dreams, they know the way",
  "Be yourself, everyone else is taken",
  "Take one day at a time",
  "Life is too short to waste time on things that don't matter",
  "Be kind, for everyone you meet is fighting a battle you know nothing about",
  "The best things in life are the people we love, the places we've been and the memories we've made along the way",
  "Every day is a new opportunity to be your best self",
  "The biggest risk is not taking one",
  "Success is not final, failure is not fatal: it's the courage to continue that counts",
  "Be yourself; everyone else is already taken",
  "Every day is a chance to make a difference",
  "Don't wait for things to happen, make them happen",
  "You only live once, make it count",
  "Life is too short to be anything but happy",
  "Be the change you wish to see in the world",
  "A positive attitude can change everything",
  "The only way to do great work is to love what you do",
  "Successful people never stop learning",
  "Happiness is not something you postpone for the future, it's something you design for the present",
  "No matter what people tell you, words and ideas can change the world",
  "Don't watch the clock, do what it does, keep going",
  "You are never too old to set another goal or to dream a new dream",
  "The only limits in life are the ones you make",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
  "Be proud of who you are and not ashamed of how someone else sees you",
  "Life is 10% what happens to us and 90% how we react to it",
  "Do not let yesterday take up too much of today",
  "Take the chance while you still have the choice",
  "The difference between ordinary and extraordinary is that little extra",
  "Success is not the key to happiness. Happiness is the key to success",
  "Your time is limited, don't waste it living someone else's life",
  "Don't let your past dictate who you are, but let it be part of who you will become",
  "Success is not how high you have climbed, but how you make a positive difference to the world",
  "Life is too short to waste on things that don't matter",
  "What you get by achieving your goals is not as important as what you become by achieving your goals",
  "Stay positive, work hard, make it happen",
  "Do what you can, with what you have, where you are",
  "It's not the years in your life that count. It's the life in your years",
  "The only way to do great work is to love what you do",
  "One day or day one, you decide",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
  "Success is not the key to happiness. Happiness is the key to success",
  "Start where you are, use what you have, do what you can",
  "The only way to do great work is to love what you do",
  "Successful people do what unsuccessful people are not willing to do",
  "Success is not final, failure is not fatal: it's the courage to continue that counts",
  "You only live once, but if you do it right, once is enough",
  "Be the change you wish to see in the world",
  "Believe in your dreams and they will become reality",
  "Life is too short to waste on things",
  "Be yourself; everyone else is already taken",
  "Life is about making choices and taking chances",
  "Positive thinking opens doors to new opportunities",
  "The only way to do great work is to love what you do",
  "Happiness is not something you postpone for the future, it's something you design for the present",
  "Successful people never stop learning",
  "Every day is a new opportunity to be your best self",
  "Life is too short to waste time on things that don't matter",
  "Take one day at a time",
  "Be kind, for everyone you meet is fighting a battle you know nothing about",
  "The best things in life are the people we love, the places we've been and the memories we've made along the way",
  "No matter what people tell you, words and ideas can change the world",
  "You are never too old to set another goal or to dream a new dream",
  "The only limits in life are the ones you make",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
  "Be proud of who you are and not ashamed of how someone else sees you",
  "Life is 10% what happens to us and 90% how we react to it",
  "Do not let yesterday take up too much of today",
  "Take the chance while you still have the choice",
  "The difference between ordinary and extraordinary is that little extra",
  "Success is not the key to happiness. Happiness is the key to success",
  "Your time is limited, don't waste it living someone else's life",
  "Don't let your past dictate who you are, but let it be part of who you will become",
  "Success is not how high you have climbed, but how you make a positive difference to the world",
  "Life is too short to waste on things that don't matter",
  "What you get by achieving your goals is not as important as what you become by achieving your goals",
  "Stay positive, work hard, make it happen",
  "Do what you can, with what you have, where you are",
  "It's not the years in your life that count. It's the life in your years",
  "One day or day one, you decide",
  "Successful people do what unsuccessful people are not willing to do",
  "Success is not final, failure is not fatal: it's the courage to continue that counts",
  "You only live once, but if you do it right, once is enough",
  "Be the change you wish to see in the world",
  "Believe in your dreams and they will become reality",
  "Life is too short to waste on things that don't matter",
  "Life is about making choices and taking chances",
  "Positive thinking opens doors to new opportunities",
  "Happiness is not something you postpone for the future, it's something you design for the present",
  "Successful people never stop learning",
  "Every day is a new opportunity to be your best self",
  "Be kind, for everyone you meet is fighting a battle you know nothing about",
  "The best things in life are the people we love, the places we've been and the memories we've made along the way",
  "No matter what people tell you, words and ideas can change the world",
  "The only limits in life are the ones you make",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
  "Be proud of who you are and not ashamed of how someone",
  "The future belongs to those who believe in the beauty of their dreams",
  "Act as if what you do makes a difference. It does",
  "The journey of a thousand miles begins with a single step",
  "You miss 100% of the shots you don't take",
  "The only way to do great work is to love what you do",
  "Success is not final, failure is not fatal: it's the courage to continue that counts",
  "Success is not how high you have climbed, but how you make a positive difference to the world",
  "Better to have tried and failed than to have never tried at all",
  "Don't let yesterday take up too much of today",
  "Never stop dreaming, never stop believing, never give up, never stop trying",
  "In order to succeed, we must first believe that we can",
  "It's not the years in your life that count. It's the life in your years",
  "Be the best version of yourself, not a copy of someone else",
  "Don't watch the clock; do what it does. Keep going",
  "Don't wait for opportunities, create them",
  "Your only limit is the amount of love you have to give",
  "The future is not something you wait for, it's something you create",
  "Don't let your fears hold you back from living your best life",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart",
  "Happiness is not something you postpone for the future, it's something you design for the present",
  "Successful people do what unsuccessful people are not willing to do",
  "Successful people never stop learning",
  "Success is not the key to happiness. Happiness is the key to success",
  "Success is not determined by what you achieve, but by the amount of effort you put in",
  "The difference between ordinary and extraordinary is that little extra",
  "The only way to do great work is to love what you do",
  "The only limits in life are the ones you make",
  "Believe in your dreams and they will become reality",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
  "Be kind, for everyone you meet is fighting a battle you know nothing about",
  "Be proud of who you are and not ashamed of how someone else sees you",
  "Be the change you wish to see in the world",
  "Life is about making choices and taking chances",
  "Life is too short to waste on things that don't matter",
  "Life is too short to waste time on things that don't matter",
  "Life is too short to waste on things that don't matter",
  "No matter what people tell you, words and ideas can change the world",
  "One day or day one, you decide",
  "Positive thinking opens doors to new opportunities",
  "Stay positive, work hard, make it happen",
  "Take one day at a time",
  "Take the chance while you still have the choice",
  "The best things in life are the people we love, the places we've been and the memories we've made along the way",
  "The journey of a thousand miles begins with a single step",
  "The only limits in life are the ones you make",
  "You are never too old to set another goal or to dream a new dream",
  "You only live once, but if you do it right, once is enough",
  "Be yourself, everyone else is already taken",
  "Do what you love, and you will never have to work a day in your life",
  "Don't let yesterday take up too much of today",
  "Every day may not be good, but there is something good in every day",
  "The greatest glory in living lies not in never falling, but in rising every time we fall",
  "Be the reason someone smiles today",
  "Believe you can and you're halfway there",
  "Chase your dreams, they know the way",
  "Don't count the days, make the days count",
  "Don't let fear stop you, let it be your motivator",
  "Don't wait for the perfect moment, take the moment and make it perfect",
  "Dream big and dare to fail",
  "Dream without fear, love without limits",
  "Everything happens for a reason",
  "Fall seven times, stand up eight",
  "Good things take time",
  "Happiness is not a destination, it's a journey",
  "I can, I will, end of story",
  "If you can dream it, you can do it",
  "If you want to fly, you have to give up what weighs you down",
  "It does not matter how slowly you go as long as you do not stop",
  "It's not the destination, it's the journey",
  "Keep your eyes on the stars, and your feet on the ground",
  "Life is 10% what happens to us and 90% how we react to it",
  "Life is too short to be anything but happy",
  "Life is too short to wait",
  "Life is what we make it",
  "Life is too short to waste on things that don't matter",
  "Life is too short to waste time on things that don't matter",
  "Life's not about waiting for the storm to pass, it's about learning to dance in the rain",
  "Never give up on something you can't go a day without thinking about",
  "Never stop learning, because life never stops teaching",
  "Not everything happens for a reason, but everything is a lesson",
  "One day at a time",
  "Positive mind, positive vibes, positive life",
  "Success is not overnight, it's a result of consistent hard work",
  "The best is yet to come",
  "The future is bright, the future is yours",
  "The only way to do great work is to love what you do",
  "The only way to make sense of change is to plunge into it, move with it, and join the dance",
  "The only way to achieve success is to keep moving forward",
  "The only way to fail is to stop trying",
  "The power of imagination makes us infinite",
  "The secret of change is to focus all of your energy, not on fighting the old, but on building the new",
  "There is no time like the present",
  "Think big and don't listen to people who tell you it can't be done",
  "Today is a new day, a new opportunity to be the best version of yourself",
  "Yesterday is history, tomorrow is a mystery, but today is a gift, that's why we call it the present",
  "You are enough, just as you are",
  "You become what you believe",
  "You can't go back and change the beginning, but you can start where you are and change the ending",
  "You don't have to be great to start, but you have to start to be great",
  "A goal without a plan is just a wish",
  "A journey of a thousand miles begins with a single step",
  "A negative mind will never give you a positive life",
  "Actions speak louder than words",
  "All good things take time",
  "All our dreams can come true, if we have the courage to pursue them",
  "An obstacle is often a stepping stone",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
  "Choose to be happy, it's a choice you make every day",
  "Create the life you want, not the life others expect of you",
  "Create the type of self that you will be happy to live with all your life",
  "Dream big, work hard, stay focused, and surround yourself with good people",
  "Each day is a blank canvas, make it a masterpiece",
  "Everything will fall into place, at the right time, with the right people",
  "Failing to plan is planning to fail",
  "Forget the past, focus on the present, create the future",
  "Great things take time, and time takes patience",
  "Hardships often prepare ordinary people for an extraordinary destiny",
  "Hope is the only thing stronger than fear",
  "I can and I will, watch me",
  "If you don't like something, change it. If you can't change it, change the way you think about it",
  "If you don't make the time to work on creating the life you want, you're eventually going to be forced to spend a lot of time dealing with a life you don't want",
  "If you want something you've never had, you have to do something you've never done",
  "In every success story, you will find someone who has made a courageous decision",
  "It takes courage to grow up and become who you really are",
  "It takes time to build a castle, but one day it will stand tall for all to see",
  "Keep moving forward, success is just around the corner",
  "Life is a journey, not a destination",
  "Life is not about waiting for the storm to pass, it's about learning to dance in the rain",
  "Life is short, live it well",
  "Life is too short to waste time on things that don't matter",
  "Life is too short to waste time on things that don't make you happy",
  "Life is what you make it, so make it a good one",
  "Life is worth living, when you have something worth living for",
  "Look for something positive in every day, even if some days you have to look a little harder",
  "Love the life you live, live the life you love",
  "Make every day a masterpiece",
  "Make every day your masterpiece",
  "Make the most of today, because yesterday is gone and tomorrow may never come",
  "Miracles happen every day, be open to them",
  "Mistakes are proof that you are trying",
  "Never give up, great things take time",
  "Never stop learning, growth starts at the end of your comfort zone",
  "No matter what people tell you, words and ideas can change the world",
  "Nothing is impossible, the word itself says 'I'm possible'",
  "One day at a time, one step at a time",
  "Our only limit is the amount of love we give",
  "People will forget what you said, people will forget what you did, but people will never forget how you made them feel",
  "Success is not final, failure is",
  "Be the change you wish to see in the world",
  "Beauty is not just skin deep, it's in the way you live your life",
  "Believe in your dreams and they may come true, believe in yourself and they will come true",
  "Better to light one small candle than to curse the darkness",
  "Change your thoughts and you change your world",
  "Don't count the memories, make the memories count",
  "Don't let yesterday take up too much of today",
  "Don't watch the clock, do what it does, keep going",
  "Dreams come a size too big so we can grow into them",
  "Every moment is a fresh beginning",
  "Every step forward is a step towards your goal",
  "Find something you love to do and you'll never have to work a day in your life",
  "Follow your heart and the universe will open doors where there were only walls",
  "Happiness is a warm hug",
  "Happiness is not something you postpone for the future, it is something you design for the present",
  "Happiness is not what you have, it's what you give",
  "Happiness is not what you receive, it's what you create",
  "Happiness is not what you see, it's what you make",
  "Happiness is not what you're given, it's what you make",
  "Happiness is the key to success",
  "Have the courage to follow your heart and intuition",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination",
  "If you can imagine it, you can achieve it",
  "If you can't find a reason to fight for, you shouldn't be fighting",
  "If you want to fly, you have to give up the things that weigh you down",
  "In a world where you can be anything, be yourself",
  "It does not matter how slowly you go as long as you do not stop",
  "It's a good day to have a good day",
  "It's not about waiting for the storm to pass, it's about learning to dance in the rain",
  "Life is a book, some chapters are sad, some are happy, and some are exciting. But if you never turn the page, you will never know what the next chapter holds",
  "Life is a canvas, paint it however you want",
  "Life is a choice, choose happiness",
  "Life is like a camera, focus on the good times, develop from the negatives, and if things don't work out, take another shot",
  "Life is not just about surviving the storm, it's about learning to dance in the rain",
  "Life is too precious to waste on things that don't matter",
  "Life is too short to be anything but happy",
  "Life is too short to waste time on things that don't make you happy",
  "Life is what happens when you're busy making other plans",
  "Life is what you make it, make it a good one",
  "Life is worth living, when you have someone worth living for",
  "Life's too short to waste time on things you don't enjoy",
  "Life's too short to waste time on things that don't make you happy",
  "Never give up on something you really want. The journey is tough, but the reward is worth it",
  "Never let yesterday take up too much of today",
  "No act of kindness, no matter how small, is ever wasted",
  "Nothing is impossible, everything is within reach",
  "Nothing is permanent in this world, not",
  "A goal without a plan is just a wish",
  "A journey of a thousand miles begins with a single step",
  "A positive attitude can change everything",
  "A smile is the universal language of kindness",
  "An obstacle is often a stepping stone to success",
  "Be yourself, everyone else is already taken",
  "Courage doesn't always roar, sometimes it's a quiet voice at the end of the day saying, I will try again tomorrow",
  "Do not let yesterday define who you are, define yourself",
  "Don't be afraid to be different, be afraid to be the same as everyone else",
  "Don't let the fear of failure hold you back",
  "Don't let the fear of the unknown hold you back",
  "Don't wait for opportunity, create it",
  "Empower yourself with education",
  "Every challenge is an opportunity in disguise",
  "Every day is a new beginning",
  "Every day is a new chance to be your best self",
  "Focus on what you can control and let go of what you can't",
  "Great things never come from comfort zones",
  "Inspiration exists, but it has to find you working",
  "It takes courage to grow up and become who you really are",
  "Life is a gift, enjoy it to the fullest",
  "Life is like a garden, what you water will grow",
  "Life is short, live it to the fullest",
  "Success is not final, failure is not fatal: it is the courage to continue that counts",
  "The future belongs to those who believe in the beauty of their dreams",
  "The only way to do great work is to love what you do",
  "The only way to make sense of change is to plunge into it, move with it, and join the dance",
];

const funnyCommit = () => {
  const message = messages[Math.floor(Math.random() * messages.length)];
  console.log(`\x1b[34m${message}\x1b[89m`);
};

module.exports = {
  funnyCommit,
};
